# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcjacobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
