# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcjacobs', '0003_auto_20170703_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcjacobs.Menu'),
        ),
    ]
