# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcjacobs', '0004_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=50),
        ),
    ]
