# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcjacobs', '0005_auto_20170704_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
